server:
  port: 8081

spring:
  application:
  name: spring-resource-server
  output.ansi.enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8099" #The issuer is the Authorization server

logging:
  level:
    org:
      springframework:
        security: trace


